title: Farhad MEHRABI
logo: /assets/img/logo.png
description: Prospective PhD Student
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github_url: https://github.com/fmehrabi
linkedin_url: https://www.linkedin.com/in/mehrabii/
researchgate_url: https://www.researchgate.net
