title: Farhad MEHRABI
logo: /assets/img/farhad.jpg
description: Prospective PhD Student
description: AI Strategy & Governance
description: Digital Strategy & Transformation
description: Technology & Innovation Management
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github_url: https://github.com/fmehrabi
linkedin_url: https://www.linkedin.com/in/mehrabii/
researchgate_url: https://www.researchgate.net
